Algoritmo      "Exercicio_Terreno"

Var
largura, comprimento, metroQuadrado,area, preco : real

Inicio
Escreva("Digite a largura do terreno:")
Leia(largura)
Escreva("Digite o comprimento do terreno:")
Leia(comprimento)
Escreva("Digite o valor do metro quadrado:")
Leia(metroQuadrado)

area <- largura * comprimento
preco <- area * metroQuadrado

escreval("Area do terreno =" ,area)
escreval("Preço do terreno =" ,preco)


Fimalgoritmo

